### ISSUE TITLE
Supporting Multiple Invoices

### ISSUE THREAD

**Issue by iamdabobo** [ABTech/abtt#104]
Any individual event may have multiple invoices associated with it.  This is used for probably under 10% of events, but when it is used, it's done in one of two ways:

1.  to have a preliminary quote/scratch quote
2.  to bill multiple accounts for one large event.  

Issue 2 is part of a larger discussion that could be had on philosophy of event splitting, which I'll open in a separate issue.  But let's focus on the desire to have multiple invoices.  

When you audit completed events, it only shows one invoice, which I believe is the first invoice created.  For scenario 2, I would need to see all the invoices in this list.  For scenario 1, I would need to see the most recently created or most recently updated invoice, though seeing both invoices (as long as they're together in the same event line) wouldn't necessarily be bad--but you'd also need to add an invoice title column.  

When you list invoices, you do see all the invoices created; however, since the list is sorted by invoice creation date, multiple invoices for an event are separate.  In scenario 1, this leads to a confusing view which could result in errors.  Fixing this would at minimum require changing the sort view to event date, which I don't think would be bad regardless, and then keeping the two invoices together with the event line.  Additionally, it would require having a column for invoice title, so that the correct invoice can be deduced.  

I don't have specific answers; I'm opening this for discussion purposes, but I am also marking it as a bug because the current behaviour of listing only the first created invoice on the audit completed events page is indeed a problem.

**Comment by hatkirby** [comment]
Closing this because the audit completed events page is going away.
