### ISSUE TITLE
Add another event date

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#193]
When creating a second sub-event (eg, creating load-in and then sound check and then show), it's kinda annoying to have to re-enter things that should be consistent across the sub-events (like the month or day or location). While there are events like the year's R&M, where a new event being current time is desirable, I think those are in the vast minority. IMO there are two good options: 

New sub-events always default to the info of the existing sub-event with the latest date.

New sub-events default to the info of the existing sub-event with the latest date, unless all sub-events are in the past - then it defaults to the current time (but keeps location?)

Thoughts?

**Comment by hatkirby** [comment]
d74fc9424dfe3a342aa3b913ff9fd706c05da36f
