### ISSUE TITLE
Improvements to member database

### ISSUE THREAD

**Issue by iamdabobo** [ABTech/abtt#195]
1.  Ability to track year in school (freshman, sophomore, junior, senior, grad, faculty)
2.  Ability to track form submission and date submitted (payroll paperwork, SSI form, driving paperwork)
3.  Ability to track key possession (none, bottom, top)
4.  Entry for alternative gmail address
5.  "Summer Tasks" button should do the following:
a. increase all pay rates of "general members" by $0.25, max $8.00
b.  reset all SSI form submission boxes
c.  reset all driving paperwork submission boxes
d.  increase all school years by one; senior -> alumni.  but there should be a verfiication page for all seniors, as a few stick around.  i.e. allow manual changing of seniors to grad, local, or alumni (default) and then update payroll accordingly (if a senior sticks around as grad, pay rate still goes up, but is also still capped at 8.00).  Alumni pay rate is 0.00

Design notes, in order for more columns to fit on the member list page:  I don't think "Title" or "Aim" are very useful - those could be removed.  "Destroy" could also be removed, and only present in the member details page.  "Show" could be removed, and the name and/or kerbid made into a link.  "Created" and "Updated" could be shown just on the member details page.  

Of the additions, driving information could be shown just on the member detail page as only a few people ever submit it.  Same for school year, as that's more for tracker to track people, and isn't really helpful for the HoT to see.  But SSI submission date, payroll paperwork submission date, and key possession should all be shown in the main list.  

SSI forms are the only of the above items that are accessed in large quantity over a varied period of time.  A way to update these from the main member list page without having to go to an individual edit page would be nice.  

All of the above information would be restricted to just Head of Tech.

**Comment by hatkirby** [comment]
Some thoughts:

1. I'm curious as to why school year is necessary. It'd require a lot of initial data entry to get everyone's school years correct, and then you encounter the problem that not everyone advances a school year after the spring semester, and that some people graduate early. It's not a huge problem but it doesn't seem like hugely necessary data to me. I could be wrong.
2. Seems good.
3. Ditto.
4. Ditto.
5. I'm trying to think about easy ways to automate the summer tasks without making it too easy to create bad data. One potential idea is to have a page with multiple sections. One section would allow the HoT to reset submit statuses of SSI forms and driving paperwork. Another section labeled "Adjust Payrate" could show a list of active non-alum members next to checkboxes indicating whether or not that person is graduating. When submitted, that section would increase the payrate (up to the max) for each unchecked member, and set to zero the payrate for each checked member. As the Alumni status of a member is related more to permissions than the member's actual status as an alumnus or not, a Bulk Set As Alumni (or possibly even just Bulk Edit Members section, which could also help with marking SSI forms as submitted at the beginning of the year) section separate from the Adjust Payrate section could also exist. If it would be simpler, that could just be merged into the Adjust Payrate section.

I agree with removing the Title and Aim fields from the list, but I think the new HoTs should comment on whether or not they should stay on the list (either way, I won't delete the data).
