### ISSUE TITLE
Timecard Generation

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#209]
Currently (I believe) the Start Date is "anything after the end of this date counts" and the End Date is "anything before the beginning of this date" ... and that's kinda silly. To my mind there's two approaches:

1. they should be either set to the same thing (probably start="anything after the start of this date counts" and end="anything after the start of this date doesn't count"), so that they can just be set two weeks apart, 
or 
2. they should be set so that events on startdate and enddate are both included. (ie, the reverse of what's done

I think at the moment I have a moderate preference for option 1, but if it's harder, I'm fine with 2 as well.

**Comment by hatkirby** [comment]
I'm not sure that it works the way you described. The start date is "any event ending after the beginning of this day is included" and the end date is "any event beginning before the beginning of this day is included." Is this the desired behavior or should it be changed?

**Comment by pchiappacmu** [comment]
This is no longer really my call, but what I wanted was for it to be unconfusing - I've had multiple times throughout the year when events that I wanted to be included in a timecard weren't or were included that I didn't want. I'm not really sure what the best way to handle that is moving forward, but IMO the option that appeals to me most is "if any part of the event touches a day in this range, listed dates inclusive, then it shows up". IE, Monday through Sunday.
