### ISSUE TITLE
Preferred Locations

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#216]
Is there any good way to do a "common locations thing", where places like Rangos 1 2 3, The Underground, etc are in a separate list/at the front of the locations list? Slash how do people feel about this?

**Comment by hatkirby** [comment]
The current locations input allows you to begin typing the name of a location to "search" for it in the list. Is this functionality enough or would you also like a sublist of the locations list at the top entitled "Favorites"?
