### ISSUE TITLE
Location Identical

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#219]
Is it possible to get a button that will make all the locations for sub-events identical? Obviously something like Fall Concert or DS has all of its crap in one location. This sort of falls together with the "preferred/frequent locations" thing. If that happened, it would pretty much nullify this.

**Comment by hatkirby** [comment]
Currently, adding a new eventdate copies the locations from the previous eventdate. Is this sufficient or would you also like a "Copy Locations From Eventdate" button (or something like that)?
