### ISSUE TITLE
Baby Tracker

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#228]
I want a tracker page I can link to, that's public, that is the front page of tracker with no links.

**Comment by mickeyreiss** [comment]
Have you seen https://tracker.abtech.org/calendar ?

**Comment by mickeyreiss** [comment]
https://tracker.abtech.org/calendar/generate.schedule is also public.

**Comment by pchiappacmu** [comment]
All the former tells someone who's not logged in is that there's an event on that day. 

The schedule generation is public and has better information, but it's pretty shitty to read - for instance, at the moment it's displaying events from January. Given that it would need changes to be useable for this purpose anyway, it makes sense to me to use the front page of tracker to keep things consistent for when newbies become real members (unless making the necessary changes to a duplicate front page is massively difficult or something.)

**Comment by tedgarb** [comment]
Would it be fair to say that what are you looking for is a copy of the front page as it exists, but without the ability to click into the actual events, and without the run positions column?

**Comment by pchiappacmu** [comment]
Uh, I don't have an issue with having the run positions column. In general I'd probably slightly prefer to have it, although I suppose it's not especially necessary if it's a problem. Otherwise sounds accurate (although obviously the header that gives you the option to go to timecards would need to not be there) .

**Comment by tedgarb** [comment]
Alright, this shouldn't be terrible to do, I'll hopefully get to it this weekend or so

**Comment by tedgarb** [comment]
Please check out https://tracker-dev.abtech.org/ when you get a chance. Currently non-members can see the main events view, monthly events view, and the public calendar.

**Comment by mickeyreiss** [comment]
In my opinion, this is a bit too much information to put out on the internet. Much of it was input thinking that it would be private, so who knows what some of the even titles, equipment names, etc. might say. Would it still be as useful if there were slightly less information made internet-public?

**Comment by pchiappacmu** [comment]
There's a number of relatively easy solutions - event titles are pretty easy to sanitize going forward, especially if unpublished events aren't listed. It doesn't look like you can use the past button, but that should be confirmed. In any case, if they can only see future events, naming shouldn't be a problem. 

I wouldn't be super worried about equipment names - is there anything offensive? Leaving off equipment is another option for other reasons, as that's something that people could look at and be like "why are these two events different equipment" and potentially get upset about. 

Also, quibble about the top text, in the vein of a lot of this discussion. This NOT for organizers. It is for new members only, and I'd be super tempted to not have it functional year round or somehow have access be vaguely restricted or something.

**Comment by tedgarb** [comment]
The past view is restricted. Currently, the month views for past months are not, but that can be adjusted relatively easily. The top text is based off of the original text for /events/calendar. I can change it, but it might be best if someone gives me a text that they want.

**Comment by mickeyreiss** [comment]
Good ideas, @pchiappacmu. I think it's looking better now.

@tedgarb I don't think the top text is necessary at all. One thing that could be helpful is a call to action that shows people the right way to request events.

One other thing to consider: Do we want to edit our [`robots.txt`](https://tracker-dev.abtech.org/robots.txt) to prevent Google from indexing the public events list?

**Comment by APinson** [comment]
I'd suggest not having every event position listed. Maybe just have the TiC listed so that, in the event that an event organizer does find this page, they'll only contact the TiC. Same with new members. In my opinion, if new members are contacting someone about an event it should be either the inbox or the TiC of that event, not individual positions for the event.

Also, I don't know how difficult it'd be to do this but omitting any positions (or at least the TiC) when we don't have a TiC might be a good idea. As it looks a little bad when we don't have an event organizer the day before or the day of show (which sometimes happens). So maybe instead of having "TIC: (unassigned)" like we currently do, maybe we could just have nothing there? Or maybe have the exec member who is "super TiC" for that day listed instead? I just think it looks bad if we are semi-publicly announcing that we don't have an event organizer for some events.

**Comment by tedgarb** [comment]
Peter: can you comment on the last two responses to this ticket?
