### ISSUE TITLE
Duplicate Events on Calendar Export

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#231]
I know I have a lot of Greek Sing this weekend....but this seems like too much. Does anyone else have this issue with the https://tracker.abtech.org/calendar/generate.ics link in google calendar?

![screenshot 2015-03-19 10 16 07](https://cloud.githubusercontent.com/assets/5491270/6732290/2a9ed3c4-ce21-11e4-9024-212fee26bc2d.png)

**Comment by APinson** [comment]
Yup...
On Mar 19, 2015 10:18 AM, "Robert Maratos" <notifications@github.com> wrote:

I know I have a lot of Greek Sing this weekend....but this seems like too
much. Does anyone else have this issue with the
https://tracker.abtech.org/calendar/generate.ics link in google calendar?

[image: screenshot 2015-03-19 10 16 07]
<https://cloud.githubusercontent.com/assets/5491270/6732290/2a9ed3c4-ce21-11e4-9024-212fee26bc2d.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/ABTech/abtt/issues/231>.
