### ISSUE TITLE
Calendar Export/Email

### ISSUE THREAD

**Issue by APinson** [ABTech/abtt#232]
So we've started sending weekly emails about events and although Baby Tracker is an awesome feature (thank you!) some people may not follow the link through and I like having all the information in the email as well. Currently we manually format our emails and then append the full text calendar (available under the "as schedule" link on the calendar page) at the end. Ideally this wouldn't happen and we would be able to have tracker spit out something (or even send an email internally) that resembles what we currently do manually.

Please see the images at the bottom of this ticket for how I formatted the most recent email. With regards to the blurbs at the top and below each event, I'd be happy to still manually write those or, as was suggested to me, maybe we could have a description attached to each event which would then be imported into this auto-generated email.

Just a few thoughts. This feature could really save a lot of time spent formatting emails.

![ab tech events_page_1](https://cloud.githubusercontent.com/assets/3346044/6774563/cd5c5008-d0f8-11e4-94a6-f82aa6bf5e5f.jpg)
![ab tech events_page_2](https://cloud.githubusercontent.com/assets/3346044/6774549/8e71ec7c-d0f8-11e4-8a3e-95520164b4b5.jpg)

**Comment by hatkirby** [comment]
Each eventdate has an "email description" field which can be edited from the event edit form, which should be a short description of the event (as in the example email provided in the ticket). Sending a weekly events email can be accomplished by going to the Email page, and clicking on "Send Weekly Email" in the sidebar. The subject, intro, and outro of the email can be customized here. You are also provided with a list of the events occurring in the next seven days, and can choose which ones to include in the email. The email description field of each eventdate is also editable from this page. Submitting the form will send the email from your email address to abtech@andrew.cmu.edu. The email was designed to look similarly to the provided example email in the ticket.

**Comment by APinson** [comment]
So I just tried the feature and it worked well! Thanks.

This said, a few things occurred to me while using the service. These things aren't incredibly important but if they're relatively easy to implement I'd certainly appreciate them:
1) The button to send the email says "save changes". I see that this then saves the updated descriptions to the events but some indication (mainly for future users) that this button also sends an email might be helpful.
2) I realize that this wasn't in the original example email but adding a "who" section that lists the TiC (or exec) assigned to an event would be helpful as well. Please see below example.

![image](https://cloud.githubusercontent.com/assets/3346044/7104453/c5817cfc-e0af-11e4-9a5b-809652f45e9d.png)

**Comment by APinson** [comment]
Awesome! Works great. Thanks!
