### ISSUE TITLE
Search scope

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#235]
I don't understand why some things come up in the search results and some don't. For instance, "carnival" does not turn up the future sns carnival rental, but it DOES turn up the future carnival event, as well as past carnival rentals. There was also a point where searching "greek sing" didn't turn up this year's GS event (that might've been where I first noticed). I don't know whether this is a bug or just arcane rules I don't understand.

**Comment by hatkirby** [comment]
This issue was caused by the search index being out of date (which I have now rebuilt, so you can for instance see the sns rental when you search for carnival). I will look into finding a way to prevent this becoming an issue again in the future.
