### ISSUE TITLE
Email Description

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#239]
Three things

Currently this shows up in the equipment/location box and shows up for all members. If possible, it should be placed in a box below the "notes" box, probably. 

It should show up for tic and exec+, not for all members. 

It doesn't show up in calendar generation?

**Comment by pchiappacmu** [comment]
Actually, currently there's email description per sub-event. I guess that's probably correct, but I feel a bit weird about it.

**Comment by hatkirby** [comment]
Having a separate description for each sub event does feel weird but it makes sense for events like Carnival where each sub event really is a different event. I can certainly restrict viewing access to exec and tic, and I can certainly add the descriptions to the generated iCal file.

**Comment by pchiappacmu** [comment]
I was commenting more on the text generation thing - ie, https://tracker-dev.abtech.org/calendar/generate.schedule?matchdate=20150413 does not show the email description. Maybe I'm looking in the wrong place? 

But yeah, I don't really see a need for it in ical export. 

And yeah, descriptions per sub event is probably correct in the end.

**Comment by hatkirby** [comment]
I have added it to both the iCal export and the text calendar export.
