### ISSUE TITLE
Update SSL Certificate

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#242]
Just a warning in chrome now but will eventually be deprecated.
![screenshot 2015-04-20 10 12 51](https://cloud.githubusercontent.com/assets/5491270/7231856/09b63d44-e746-11e4-88ee-76874d60eaba.png)

https://www.ssllabs.com/ssltest/analyze.html?d=tracker.abtech.org

**Comment by hatkirby** [comment]
Certificate is updated for tracker.abtech.org, still waiting on certificate authority for new certificate for tracker-dev.
