### ISSUE TITLE
New Event Editing Page

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#245]
http://i.imgur.com/MULda0W.png

The text lines don't seem to line up with the corresponding options. It seems somewhat regular, not like a slow shift, but I'd strongly prefer to not have something where the text boxes are slightly above the line, check boxes signficantly above, notes doing its own weird thing ...

**Comment by hatkirby** [comment]
https://www.dropbox.com/s/0s3dfoggv3srjbq/Screenshot%202015-05-03%2015.52.44.png?dl=0

Does this look better?

**Comment by pchiappacmu** [comment]
Much!
