### ISSUE TITLE
Event date layout

### ISSUE THREAD

**Issue by pchiappacmu** [ABTech/abtt#247]
http://i.imgur.com/CN4d8ji.png

So I'm not really a fan of this arrangement. I like the "date options only appear as needed", but this is kinda ungainly.

**Comment by hatkirby** [comment]
Do you think it would look better if the date options appeared on a new line?

**Comment by pchiappacmu** [comment]
That's probably the best option, unless there's one I'm not thinking of.

**Comment by pchiappacmu** [comment]
I think this looks really good for now, but in the long term (and at the discretion of actual students, you might consider flipping it so that when you say "literal" the actual timebox gets put at the "call/strike" line and the "literal" choice goes to the line below. Dunno if that'll actually look better or not.
