### ISSUE TITLE
event show_email view does not show full email chains

### ISSUE THREAD

**Issue by tedgarb** [ABTech/abtt#250]
When looking at the emails associated with an event, as a result of the hiding of what is being replied to, I can only see organizer responses and not what they are actually responding to. For example, https://tracker.abtech.org/events/2288/show_email .

**Comment by hatkirby** [comment]
Just a quick response; in the rewrite I'm doing, execs and TiCs will be able to send emails from tracker and tracker will then be able to store those replies in its system for easier viewing. I can also have an option to toggle hiding quotes in emails if you'd like.

**Comment by tedgarb** [comment]
It might be good to make the toggle "no quoted content/1 level of quotes/all levels of quotes" instead of just "condensed/full." It also might be nice if we could pull sent mail in addition to the inbox.
