### ISSUE TITLE
Shibbolize member login 

### ISSUE THREAD

**Issue by hatkirby** [ABTech/abtt#259]

**Comment by rmaratos** [comment]
This should happen @tedgarb @merichar

**Comment by tedgarb** [comment]
Code is done and key/cert are on the machine, we just need to get shib cert into the metadata. Last time we asked we needed to modify the abtech.org whois data to get incommon to bless the domain as being part of CMU.

**Comment by hatkirby** [comment]
Any progress on this?

**Comment by tedgarb** [comment]
Nope

**Comment by merichar** [comment]
I've got a tech systems day coming up. Should be able to take care of this
then.

**Comment by hatkirby** [comment]
Any updates on this?

**Comment by tedgarb** [comment]
*violently throws mic out of a window*
