### ISSUE TITLE
Can't create invoices for some events

### ISSUE THREAD

**Issue by fizz-wuzz** [ABTech/abtt#266]
Is there a time limit for how far back an event can go when creating invoices? When I try to create an invoice for precollege, it gives me the following error:

>2 errors prohibited this invoice from being saved:

>    Event can't be blank
>    Event can't be blank

I've also noticed previously that when the event status is set to certain values e.g. "Details Requested", the same error appears.

**Comment by hatkirby** [comment]
The problem with creating an invoice for pre-college is that the start date of its first eventdate is before July 1st, which is tracker's "magic date" for the start of the school year. It doesn't allow you to create invoices for events not in the current school year. Tracker does not make this obvious at all and the way in which it's failing for you is buggy. I could either make the issue clearer, or just remove the restriction and let you create invoices for whenever you want.

I haven't been able to reproduce the "Details Requested" bug. Can you give me an example of an event for which that happens?

**Comment by fizz-wuzz** [comment]
It makes sense to not allow the creation of invoices for events not in the current school year. I think a clearer error message will help. 

For Demosplash, I couldn't create an invoice when it was set to "Details Requested".

**Comment by hatkirby** [comment]
I have been having trouble reproducing the error with Demosplash. Can you let me know the next time it happens so I can diagnose the problem?

**Comment by fizz-wuzz** [comment]
I can't reproduce it either. Will let you know next time, thanks!
