### ISSUE TITLE
Add new equipment button -> We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#277]
Steps to reproduce:

Go to https://tracker.abtech.org/equipment

Click Add new equipment

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

My guess is I don't have rights to add new equipment which is fine, but I shouldn't see that button if that's the case.

**Comment by hatkirby** [comment]
Yeah, Exec positions can see equipment but not edit it; only Tracker Management and Head of Tech can do that. I will fix the problem with the link showing up when it shouldn't.
