### ISSUE TITLE
Automated event creation from abtech.org 

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#286]
When someone fills out the event request form at https://www-staging.abtech.org/request
it will currently send an email to them and abtech@andrew.cmu.edu filling in the following template:
https://github.com/ABTech/abtech.org/blob/master/templates/email/event.txt

I'd like tracker to either auto-parse these emails or provide an API endpoint for abtech.org to create the event on tracker. Let me know which you'd prefer.

**Comment by tedgarb** [comment]
Let's defer this until we decide if we are actually moving tracker to the colo server - might be easiest to do this by providing a limited access db account that can just insert tentative events, and this is easier if everything winds up on the same server.

**Comment by rmaratos** [comment]
Any update on this? We're getting a growing number of requests from the website form and copy-pasting all the info is annoying.

**Comment by rmaratos** [comment]
Any update on this? I'm expecting a tidal wave of requests from the website form at some point over the next few weeks. If we could make a temporary hack (which will obviously last a few generations) to make this work that'd be great.

**Comment by rmaratos** [comment]
that tidal wave had an updated forecast of tomorrow so I made something workable today
