### ISSUE TITLE
iPhone view is broken

### ISSUE THREAD

**Issue by EmNewman** [ABTech/abtt#289]
https://imgur.com/a/JL9qL

**Comment by EmNewman** [comment]
I mean the link, you can still use the desktop version on your phone

**Comment by timparenti** [comment]
iPhone view deprecated; dup of #272.

**Comment by tedgarb** [comment]
Yeah, I don't think iPhone view is going to be recreated until we have time to do major UI overhaul. Gonna close this for now cause I'm pretty sure its been ripped out of master, we just are really behind on deploys to production :(
