### ISSUE TITLE
Exec and Tracker Management Can't Add New Member

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#290]
They can see the form, but not all of the fields. Payrate is a required field so they can't submit the form. I can just make them HoT...but it'd be cool if anyone on exec could just see the payrate form.

**Comment by rmaratos** [comment]
To clarify. Exec cannot see the add member button, and tracker management can get to the form but not see payrate.

**Comment by hatkirby** [comment]
To clarify further, do you want me to give tracker management the ability to manage payrate, and give member-editing permissions to exec?

**Comment by rmaratos** [comment]
I just want one (or more) members of exec to be able to add members to tracker. Whatever the easiest way to accomplish that is fine. We could just make the default pay rate $7.25 so it doesn't throw an error for a hidden field.

If tracker management has all of the permissions of exec and more we can just add payrate to tracker management.
