### ISSUE TITLE
Event Creation Stalls on Chrome

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#294]
This is a really weird bug...
When I click submit to create an event the page load of the completion page stalls. The event is created, but the page never loads.

Could reproduce multiple times on Chrome Version 52 on Mac OS Sierra. Safari didn't have the issue. Can test on other machines, but can you think of any recent changes that would cause this?

<img width="837" alt="screenshot 2016-08-29 13 57 49" src="https://cloud.githubusercontent.com/assets/5491270/18061468/cf56654c-6df0-11e6-8ac1-c091c4045265.png">

**Comment by hatkirby** [comment]
I recently upgraded tracker to Rails 5, so it's possible that there's some weird new JavaScript nonsense in an automatically included gem causing difficult-to-reproduce bugs in the vein of the turbolinks stuff with Rails 3 (#145). I can try to look into that. For what it's worth, I can't reproduce this on Chrome 51 on my Mac (OS X El Capitan).

**Comment by hatkirby** [comment]
Update: I upgraded to Chrome 52 and now I can reproduce the issue.

**Comment by rmaratos** [comment]
Well, glad you can reproduce it at least. :)

**Comment by rmaratos** [comment]
Event updates on Safari are also being really slow

**Comment by rmaratos** [comment]
Everything is being slow everywhere. :(

**Comment by rmaratos** [comment]
When an new event creation is stalling, it seems to impact the page load time of the homepage.

**Comment by hatkirby** [comment]
I'm pretty sure the problem is with the event search indexer. It's causing a large number of SQL statements to be executed and therefore the queries that the homepage makes are delayed. I'm going soon to try to look into what's wrong with the search engine.

**Comment by hatkirby** [comment]
I'm experiencing this on my local machine with debug logging enabled; the last thing printed before the page hangs is Sphinx reindexing the eventdate index. Example:
```
   (12.4ms)  COMMIT
Sphinx 2.2.10-id64-release (2c212e0)
Copyright (c) 2001-2015, Andrew Aksyonoff
Copyright (c) 2008-2015, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/Users/hatkirby/Dropbox/Programming/abtt/config/development.sphinx.conf'...
indexing index 'eventdate_delta'...
collected 2 docs, 0.0 MB
sorted 0.0 Mhits, 100.0% done
total 2 docs, 167 bytes
total 0.032 sec, 5211 bytes/sec, 62.40 docs/sec
total 8 reads, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
total 12 writes, 0.000 sec, 0.1 kb/call avg, 0.0 msec/call avg
  Sphinx  Retrying query "UPDATE eventdate_core SET sphinx_deleted = 1 WHERE id = 12168" after error: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (60) - UPDATE eventdate_core SET sphinx_deleted = 1 WHERE id = 12168
  Sphinx  Retrying query "UPDATE eventdate_core SET sphinx_deleted = 1 WHERE id = 12168" after error: Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (61) - UPDATE eventdate_core SET sphinx_deleted = 1 WHERE id = 12168
Redirected to http://localhost:3000/events/2506
Completed 302 Found in 120142ms (ActiveRecord: 20.8ms)
```

The page hangs right before the "Retrying query" line; after maybe a minute the page loaded and it printed those lines.

**Comment by hatkirby** [comment]
Deployed a fix for this; let me know if it seems to be working.

**Comment by rmaratos** [comment]
It now finishes. Might be slower than before? It took 6 seconds to create an event, but good enough.

**Comment by tedgarb** [comment]
Reopening this because performance is still pretty bad. Just took about 30 seconds to add a new eventdate to the existing demosplash minute.

**Comment by rmaratos** [comment]
aw, new event creation is stalling again. :(

**Comment by hatkirby** [comment]
Will look into this when I'm dying less from homework.

**Comment by hatkirby** [comment]
On local, edited an event with one eventdate and add a second one. Page hanged. Development log showed individual SQL statements updating the delta flag for an extremely large number of eventdates, after which Sphinx reindexed and restarted a large number of times (likely once per eventdate that had its delta flag set). This took quite a while, and when it finished, the page loaded.

**Comment by hatkirby** [comment]
Pushed a new fix for this, let me know how it works.

**Comment by hatkirby** [comment]
Any updates on this?

**Comment by rmaratos** [comment]
I think we're good.
