### ISSUE TITLE
Copy event date button doesn't work after error.

### ISSUE THREAD

**Issue by agotsis** [ABTech/abtt#297]
The "Copy Start Date" does not work for Call time after updating an event fails with the error "Eventdates calldate must be within two days strictly prior to the event starting".

Issue is reproducible.

<img width="604" alt="screen shot 2016-09-06 at 8 39 11 pm" src="https://cloud.githubusercontent.com/assets/15185609/18295833/c58edc96-7472-11e6-9cb1-1af3985f1a5d.png">

**Comment by rmaratos** [comment]
This might be related, but after an error, the Location of an event date is cleared. The equipment field however, isn't cleared. It would be best if the location field would remain as well.

**Comment by hatkirby** [comment]
Robert's error is unrelated: #299
