### ISSUE TITLE
Give everyone a raise on tracker

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#301]
The new payroll structure is:

New members start at $8.25/hour. Each school year that you are on Tech, you receive a $0.25/hour raise. Becoming HoT gets you an additional $1/hour raise (intended to offset the fact that HoTs do not submit hours for time spent on administrative duties outside of events).
For the 2016-2017 school year, these are the payrates:
$8.25/hr if this is your 1st year on Tech
$8.50/hr if this is your 2nd year on Tech
$8.75/hr if this is your 3rd year on Tech
$9.00/hr if this is your 4th (or later) year on Tech

**Comment by hatkirby** [comment]
I can change the functioning of the increase payrate button in bulk edit as well as the default payrate. If you haven't updated anyone's payrate to reflect the new structure yet I can also just add a dollar to all of the nonzero payrates.

**Comment by rmaratos** [comment]
All of those things would be great. thanks!
