### ISSUE TITLE
Event export

### ISSUE THREAD

**Issue by kicohen** [ABTech/abtt#307]
Can the default event export dates on the calendar page be current Sunday to next Sunday. 

No big deal but would make life easier. <3

**Comment by timparenti** [comment]
Considering the default is a period of 11 months, suggesting it be changed to 7 days seems wrong. If convenient access to exports from various periods are routinely needed, I would instead suggest nearby "quick links" for "current week", "current month", etc.

**Comment by hatkirby** [comment]
Is this for sending the weekly email? Because there is built-in functionality for that: https://tracker.abtech.org/emails/weekly

**Comment by tedgarb** [comment]
I'm going to say "no." The intention of that default is that people who use it for calendar import get most future events into their calendars at any given time. Changing this would completely break that functionality.

**Comment by hatkirby** [comment]
I think he meant the "range" option, not the "soon" option, which is the rotating one that people use in their calendar apps.
