### ISSUE TITLE
aHole is not considered an assistant position to Hole

### ISSUE THREAD

**Issue by weihang7** [ABTech/abtt#315]
As Hole, I cannot add/assign people to the aHole position.

**Comment by hatkirby** [comment]
Having trouble reproducing this error on dev and staging. I took a look at tracker and you're set as aHole, not Hole, on the ICCA event; is that what the problem is?

**Comment by timparenti** [comment]
[`EventRole.assistants`](https://github.com/ABTech/abtt/blob/cef37553201a0b5c8452f030c7059c730b73e343/app/models/event_role.rb#L109) and [`EventRole.superior`](https://github.com/ABTech/abtt/blob/cef37553201a0b5c8452f030c7059c730b73e343/app/models/event_role.rb#L145) seem to handle this correctly...

**Comment by weihang7** [comment]
@hatkirby I was Hole and I don't know if I saw a Add Roles button. I might've just been dumb though.
