### ISSUE TITLE
New Event Status: Social

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#317]
Currently using billing pending as a hack to have a different color to denote social events. Would be nice if it had its own event status and color. Welcome to suggestions.

**Comment by kicohen** [comment]
Suggested styling for social events.

<img width="1134" alt="screen shot 2017-03-30 at 3 03 59 pm" src="https://cloud.githubusercontent.com/assets/13687950/24522526/d7ebb2d8-155d-11e7-9674-b990f41f02ec.png">

**Comment by kicohen** [comment]
Ping on this. Event doesn't have to be styled that way, but it would be nice to have a social designation.

**Comment by timparenti** [comment]
Rolling this into the broader conversation at #341.

**Comment by tedgarb** [comment]
Closing for above
