### ISSUE TITLE
"We're sorry, but something went wrong." On every event update

### ISSUE THREAD

**Issue by rmaratos** [ABTech/abtt#321]
Event update does get committed, but it goes to the something went wrong screen after you hit save

**Comment by plima101** [comment]
I billing emails are not sending if I want to mark it as billing pending at the same time.

**Comment by hatkirby** [comment]
I fixed the event update problem. Is there an error message with the billing email bug? Or does it just not send? Does it also not mark as billing pending?

**Comment by plima101** [comment]
It marks billing pending but throws the tracker error before the email is sent

**Comment by hatkirby** [comment]
Oh, so it's probably the same bug as this one.
