### ISSUE TITLE
Timecard due 04/03 showing as current instead of submitted

### ISSUE THREAD

**Issue by lbressler13** [ABTech/abtt#324]
On the "Timecard" page, the timecards due on both 04/03 and 04/17 are showed in the main area under "Listing timecard entries." The timecard due 04/03 is not on the list of "Submitted timecards." The timecard due 04/03 can still be edited, and events that happened in the two weeks before 04/03 are on the list of events that can be added to a timecard.

**Comment by rmaratos** [comment]
Fixed. I have to manually check "submitted" for every timecard period...
