### ISSUE TITLE
Event Status - Academic / Holiday

### ISSUE THREAD

**Issue by kicohen** [ABTech/abtt#338]
Would it be possible to be able to designate an event an academic/holiday event for things like midsemester break and thanksgiving break and winter break?

**Comment by tedgarb** [comment]
With this, #332, #317 , should we be moving toward event "types" rather than status? We can't keep beating the stoplight metaphor horse into all of this stuff.

**Comment by kicohen** [comment]
I don't think that a type field would fix all the issues because I think that an event would still need a type and midsemester break would not fit into any of the status categories (event completed, billing pending, or initial request). We currently use those pretty vaguely. I think that adding a social and a holiday status would be fine or we could just add a "Calendar Only" status so that it was a placeholder for social and other things we wanted to show on tracker but not be public or relating to other orgs.

**Comment by weihang7** [comment]
Why not have a type field **and** a status field?

**Comment by tedgarb** [comment]
Coming back to this specific issue, can someone please explain what the difference is between the proposed event type and blackouts?

**Comment by weihang7** [comment]
Good point. Maybe we shouldn't create this type of events as actual events (and instead as blackouts) since they are not actual events.
