### ISSUE TITLE
Ima Noob

### ISSUE THREAD

**Issue by kicohen** [ABTech/abtt#345]
Ima Noob shouldn't show up on List Members By Run Position.

**Comment by weihang7** [comment]
I think it should. It's useful for keeping track of how many times people outside of Tech has taken different run positions.

**Comment by timparenti** [comment]
Let's try not to special-case the placeholder users any more than they already are.  This still conveys useful information.

**Comment by kicohen** [comment]
Guess we decided this was a non-issue.
