### ISSUE TITLE
Supervise Run Position

### ISSUE THREAD

**Issue by kicohen** [ABTech/abtt#350]
Can we create a new run position to go with the setup, strike category called Supervise.

**Comment by EmNewman** [comment]
what does this mean?

**Comment by EmNewman** [comment]
@kicohen see question?

**Comment by kicohen** [comment]
One of the biggest parts of accountability in my opinion is clear requirements and I think that the TiC position in many cases has a lot of requirements and in many others we use it as a catch all for someone to show up and supervise. And I think that these requirements become blurred as we stretch the definition of TiC and this is meant to divide up the two roles better. I also don't think that Supervise necessarily has to be the title but I think there needs to be something.

**Comment by EmNewman** [comment]
Okay, I don't really think that should stay the name, but will have to think about alternatives... they might make themselves more apparent as the role solidifies, anyway.
