### ISSUE TITLE
URGENT email filing broken

### ISSUE THREAD

**Issue by tedgarb** [ABTech/abtt#359]
Email filing is broken. All of the ajax uses a root URL of /, but we need it to respect Rails.application.config.action_controller.relative_url_root so that it calls the right path based on what environment it is running in. This is preventing all email filing at least, based on IE the URL in
https://github.com/ABTech/abtt/blob/6051838a70021273b599e701da56aca6fb601729/app/assets/javascripts/emails.js.coffee#L79

**Comment by hatkirby** [comment]
Forgot to add the right tag while committing, but fixed in 786629d and 4ae035f
